/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   symbols.h                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maiboyer <maiboyer@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/04/14 19:17:54 by maiboyer          #+#    #+#             */
/*   Updated: 2024/04/14 19:18:20 by maiboyer         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef SYMBOLS_H
# define SYMBOLS_H

enum e_symbols {
	sym_word = 1,
	anon_sym_LBRACE = 2,
	anon_sym_RBRACE = 3,
	anon_sym_LPAREN = 4,
	anon_sym_RPAREN = 5,
	anon_sym_PIPE = 6,
	anon_sym_AMP_AMP = 7,
	anon_sym_PIPE_PIPE = 8,
	anon_sym_BANG = 9,
	anon_sym_EQ = 10,
	anon_sym_LT = 11,
	anon_sym_GT = 12,
	anon_sym_GT_GT = 13,
	anon_sym_LT_LT = 14,
	aux_sym_heredoc_redirect_token1 = 15,
	anon_sym_DOLLAR_LPAREN_LPAREN = 16,
	anon_sym_RPAREN_RPAREN = 17,
	anon_sym_PLUS = 18,
	anon_sym_DASH = 19,
	anon_sym_STAR = 20,
	anon_sym_SLASH = 21,
	anon_sym_PERCENT = 22,
	anon_sym_QMARK = 23,
	anon_sym_COLON = 24,
	anon_sym_DASH2 = 25,
	anon_sym_PLUS2 = 26,
	anon_sym_PLUS_PLUS = 27,
	anon_sym_DASH_DASH = 28,
	aux_sym_concatenation_token1 = 29,
	anon_sym_DOLLAR = 30,
	anon_sym_DQUOTE = 31,
	sym_string_content = 32,
	sym_raw_string = 33,
	sym_number = 34,
	anon_sym_POUND = 35,
	anon_sym_DOLLAR_LBRACE = 36,
	anon_sym_COLON_DASH = 37,
	anon_sym_DASH3 = 38,
	anon_sym_COLON_EQ = 39,
	anon_sym_EQ2 = 40,
	anon_sym_COLON_QMARK = 41,
	anon_sym_QMARK2 = 42,
	anon_sym_COLON_PLUS = 43,
	anon_sym_PLUS3 = 44,
	anon_sym_PERCENT_PERCENT = 45,
	aux_sym__expansion_regex_token1 = 46,
	anon_sym_DOLLAR_LPAREN = 47,
	anon_sym_BQUOTE = 48,
	sym_comment = 49,
	sym__comment_word = 50,
	aux_sym__simple_variable_name_token1 = 51,
	aux_sym__multiline_variable_name_token1 = 52,
	anon_sym_AT = 53,
	anon_sym_0 = 54,
	aux_sym__word_no_brace_token1 = 55,
	anon_sym_SEMI = 56,
	anon_sym_SEMI_SEMI = 57,
	aux_sym_terminator_token1 = 58,
	sym_file_descriptor = 59,
	sym__empty_value = 60,
	sym__concat = 61,
	sym_variable_name = 62,
	sym_regex = 63,
	sym__expansion_word = 64,
	sym_extglob_pattern = 65,
	sym__bare_dollar = 66,
	sym__immediate_double_hash = 67,
	sym___error_recovery = 68,
	sym_program = 69,
	sym__statements = 70,
	aux_sym__terminated_statement = 71,
	sym__statement_not_pipeline = 72,
	sym_redirected_statement = 73,
	sym_compound_statement = 74,
	sym_subshell = 75,
	sym_pipeline = 76,
	sym_list = 77,
	sym_negated_command = 78,
	sym_command = 79,
	sym_command_name = 80,
	sym_variable_assignment = 81,
	sym__variable_assignments = 82,
	sym_file_redirect = 83,
	sym_heredoc_redirect = 84,
	sym_arithmetic_expansion = 85,
	sym__arithmetic_expression = 86,
	sym_arithmetic_literal = 87,
	sym_arithmetic_binary_expression = 88,
	sym_arithmetic_ternary_expression = 89,
	sym_arithmetic_unary_expression = 90,
	sym_arithmetic_postfix_expression = 91,
	sym_arithmetic_parenthesized_expression = 92,
	sym_concatenation = 93,
	sym_string = 94,
	sym_simple_expansion = 95,
	sym_expansion = 96,
	sym__expansion_body = 97,
	sym__expansion_expression = 98,
	sym__expansion_regex = 99,
	sym__concatenation_in_expansion = 100,
	sym_command_substitution = 101,
	sym__word_no_brace = 102,
	sym_terminator = 103,
	aux_sym__statements_repeat1 = 104,
	aux_sym_redirected_statement_repeat1 = 105,
	aux_sym_redirected_statement_repeat2 = 106,
	aux_sym_pipeline_repeat1 = 107,
	aux_sym_command_repeat1 = 108,
	aux_sym_command_repeat2 = 109,
	aux_sym__variable_assignments_repeat1 = 110,
	aux_sym_file_redirect_repeat1 = 111,
	aux_sym_concatenation_repeat1 = 112,
	aux_sym_string_repeat1 = 113,
	aux_sym__expansion_regex_repeat1 = 114,
	aux_sym__concatenation_in_expansion_repeat1 = 115,
};

#endif // SYMBOLS_H
