/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   symbols_names.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maiboyer <maiboyer@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/04/14 19:17:54 by maiboyer          #+#    #+#             */
/*   Updated: 2024/04/14 19:18:20 by maiboyer         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../types/type_symbols_names.h"
#include "../headers/symbols.h"
#include "../headers/external_scanner_symbol_identifiers.h"
#include "../headers/field_identifiers.h"

#include "../headers/constants.h"

static const \
t_symbols_names_array	g_t_symbols_names_array = {.a = {
[ts_builtin_sym_end] = "end",
[sym_word] = "word",
[anon_sym_LBRACE] = "{",
[anon_sym_RBRACE] = "}",
[anon_sym_LPAREN] = "(",
[anon_sym_RPAREN] = ")",
[anon_sym_PIPE] = "|",
[anon_sym_AMP_AMP] = "operator",
[anon_sym_PIPE_PIPE] = "operator",
[anon_sym_BANG] = "!",
[anon_sym_EQ] = "=",
[anon_sym_LT] = "operator",
[anon_sym_GT] = "operator",
[anon_sym_GT_GT] = "operator",
[anon_sym_LT_LT] = "operator",
[aux_sym_heredoc_redirect_token1] = "heredoc_delimiter",
[anon_sym_DOLLAR_LPAREN_LPAREN] = "$((",
[anon_sym_RPAREN_RPAREN] = "))",
[anon_sym_PLUS] = "operator",
[anon_sym_DASH] = "operator",
[anon_sym_STAR] = "operator",
[anon_sym_SLASH] = "operator",
[anon_sym_PERCENT] = "operator",
[anon_sym_QMARK] = "\\\?",
[anon_sym_COLON] = ":",
[anon_sym_DASH2] = "operator",
[anon_sym_PLUS2] = "operator",
[anon_sym_PLUS_PLUS] = "operator",
[anon_sym_DASH_DASH] = "operator",
[aux_sym_concatenation_token1] = "``",
[anon_sym_DOLLAR] = "$",
[anon_sym_DQUOTE] = "\\\"",
[sym_string_content] = "string_content",
[sym_raw_string] = "raw_string",
[sym_number] = "number",
[anon_sym_POUND] = "operator",
[anon_sym_DOLLAR_LBRACE] = "${",
[anon_sym_COLON_DASH] = "operator",
[anon_sym_DASH3] = "operator",
[anon_sym_COLON_EQ] = "operator",
[anon_sym_EQ2] = "operator",
[anon_sym_COLON_QMARK] = "operator",
[anon_sym_QMARK2] = "operator",
[anon_sym_COLON_PLUS] = "operator",
[anon_sym_PLUS3] = "operator",
[anon_sym_PERCENT_PERCENT] = "operator",
[aux_sym__expansion_regex_token1] = "regex",
[anon_sym_DOLLAR_LPAREN] = "$(",
[anon_sym_BQUOTE] = "`",
[sym_comment] = "comment",
[sym__comment_word] = "word",
[aux_sym__simple_variable_name_token1] = "variable_name",
[aux_sym__multiline_variable_name_token1] = "variable_name",
[anon_sym_AT] = "special_variable_name",
[anon_sym_0] = "special_variable_name",
[aux_sym__word_no_brace_token1] = "_word_no_brace_token1",
[anon_sym_SEMI] = ";",
[anon_sym_SEMI_SEMI] = ";;",
[aux_sym_terminator_token1] = "terminator_token1",
[sym_file_descriptor] = "file_descriptor",
[sym__empty_value] = "_empty_value",
[sym__concat] = "_concat",
[sym_variable_name] = "variable_name",
[sym_regex] = "regex",
[sym__expansion_word] = "word",
[sym_extglob_pattern] = "extglob_pattern",
[sym__bare_dollar] = "word",
[sym__immediate_double_hash] = "operator",
[sym___error_recovery] = "__error_recovery",
[sym_program] = "program",
[sym__statements] = "_statements",
[aux_sym__terminated_statement] = "_terminated_statement",
[sym__statement_not_pipeline] = "_statement_not_pipeline",
[sym_redirected_statement] = "redirected_statement",
[sym_compound_statement] = "compound_statement",
[sym_subshell] = "subshell",
[sym_pipeline] = "pipeline",
[sym_list] = "list",
[sym_negated_command] = "negated_command",
[sym_command] = "command",
[sym_command_name] = "command_name",
[sym_variable_assignment] = "variable_assignment",
[sym__variable_assignments] = "_variable_assignments",
[sym_file_redirect] = "file_redirect",
[sym_heredoc_redirect] = "heredoc_redirect",
[sym_arithmetic_expansion] = "arithmetic_expansion",
[sym__arithmetic_expression] = "_arithmetic_expression",
[sym_arithmetic_literal] = "arithmetic_literal",
[sym_arithmetic_binary_expression] = "arithmetic_binary_expression",
[sym_arithmetic_ternary_expression] = "arithmetic_ternary_expression",
[sym_arithmetic_unary_expression] = "arithmetic_unary_expression",
[sym_arithmetic_postfix_expression] = "arithmetic_postfix_expression",
[sym_arithmetic_parenthesized_expression] = "arithmetic_parenthesized_expression",
[sym_concatenation] = "concatenation",
[sym_string] = "string",
[sym_simple_expansion] = "simple_expansion",
[sym_expansion] = "expansion",
[sym__expansion_body] = "_expansion_body",
[sym__expansion_expression] = "_expansion_expression",
[sym__expansion_regex] = "_expansion_regex",
[sym__concatenation_in_expansion] = "concatenation",
[sym_command_substitution] = "command_substitution",
[sym__word_no_brace] = "word2",
[sym_terminator] = "terminator",
[aux_sym__statements_repeat1] = "_statements_repeat1",
[aux_sym_redirected_statement_repeat1] = "redirected_statement_repeat1",
[aux_sym_redirected_statement_repeat2] = "redirected_statement_repeat2",
[aux_sym_pipeline_repeat1] = "pipeline_repeat1",
[aux_sym_command_repeat1] = "command_repeat1",
[aux_sym_command_repeat2] = "command_repeat2",
[aux_sym__variable_assignments_repeat1] = "_variable_assignments_repeat1",
[aux_sym_file_redirect_repeat1] = "file_redirect_repeat1",
[aux_sym_concatenation_repeat1] = "concatenation_repeat1",
[aux_sym_string_repeat1] = "string_repeat1",
[aux_sym__expansion_regex_repeat1] = "_expansion_regex_repeat1",
[aux_sym__concatenation_in_expansion_repeat1] = "_concatenation_in_expansion_repeat1",
}};

const t_symbols_names_array	*create_symbols_names(void)
{
	return (&g_t_symbols_names_array);
}
