/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   primary_state_ids.h                                :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maiboyer <maiboyer@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/04/14 19:17:54 by maiboyer          #+#    #+#             */
/*   Updated: 2024/04/14 19:18:20 by maiboyer         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef PRIMARY_STATE_IDS_H
# define PRIMARY_STATE_IDS_H

# include "../types/type_primary_state_ids.h"
# include "../headers/symbols.h"
# include "../headers/external_scanner_symbol_identifiers.h"
# include "../headers/field_identifiers.h"

# include "../headers/constants.h"

void	primary_state_ids_0(t_primary_state_ids_array *v);
void	primary_state_ids_1(t_primary_state_ids_array *v);
void	primary_state_ids_2(t_primary_state_ids_array *v);
void	primary_state_ids_3(t_primary_state_ids_array *v);
void	primary_state_ids_4(t_primary_state_ids_array *v);
void	primary_state_ids_5(t_primary_state_ids_array *v);
void	primary_state_ids_6(t_primary_state_ids_array *v);
void	primary_state_ids_7(t_primary_state_ids_array *v);
void	primary_state_ids_8(t_primary_state_ids_array *v);
void	primary_state_ids_9(t_primary_state_ids_array *v);
void	primary_state_ids_10(t_primary_state_ids_array *v);
void	primary_state_ids_11(t_primary_state_ids_array *v);
void	primary_state_ids_12(t_primary_state_ids_array *v);
void	primary_state_ids_13(t_primary_state_ids_array *v);
void	primary_state_ids_14(t_primary_state_ids_array *v);
void	primary_state_ids_15(t_primary_state_ids_array *v);
void	primary_state_ids_16(t_primary_state_ids_array *v);
void	primary_state_ids_17(t_primary_state_ids_array *v);
void	primary_state_ids_18(t_primary_state_ids_array *v);
void	primary_state_ids_19(t_primary_state_ids_array *v);
void	primary_state_ids_20(t_primary_state_ids_array *v);
void	primary_state_ids_21(t_primary_state_ids_array *v);
void	primary_state_ids_22(t_primary_state_ids_array *v);
void	primary_state_ids_23(t_primary_state_ids_array *v);
void	primary_state_ids_24(t_primary_state_ids_array *v);
void	primary_state_ids_25(t_primary_state_ids_array *v);
void	primary_state_ids_26(t_primary_state_ids_array *v);
void	primary_state_ids_27(t_primary_state_ids_array *v);
void	primary_state_ids_28(t_primary_state_ids_array *v);
void	primary_state_ids_29(t_primary_state_ids_array *v);
void	primary_state_ids_30(t_primary_state_ids_array *v);
void	primary_state_ids_31(t_primary_state_ids_array *v);
void	primary_state_ids_32(t_primary_state_ids_array *v);
void	primary_state_ids_33(t_primary_state_ids_array *v);
void	primary_state_ids_34(t_primary_state_ids_array *v);
void	primary_state_ids_35(t_primary_state_ids_array *v);
void	primary_state_ids_36(t_primary_state_ids_array *v);
void	primary_state_ids_37(t_primary_state_ids_array *v);
void	primary_state_ids_38(t_primary_state_ids_array *v);
void	primary_state_ids_39(t_primary_state_ids_array *v);
void	primary_state_ids_40(t_primary_state_ids_array *v);
void	primary_state_ids_41(t_primary_state_ids_array *v);
void	primary_state_ids_42(t_primary_state_ids_array *v);
void	primary_state_ids_43(t_primary_state_ids_array *v);
void	primary_state_ids_44(t_primary_state_ids_array *v);
void	primary_state_ids_45(t_primary_state_ids_array *v);
void	primary_state_ids_46(t_primary_state_ids_array *v);
void	primary_state_ids_47(t_primary_state_ids_array *v);
void	primary_state_ids_48(t_primary_state_ids_array *v);
void	primary_state_ids_49(t_primary_state_ids_array *v);
void	primary_state_ids_50(t_primary_state_ids_array *v);
void	primary_state_ids_51(t_primary_state_ids_array *v);
void	primary_state_ids_52(t_primary_state_ids_array *v);
void	primary_state_ids_53(t_primary_state_ids_array *v);
void	primary_state_ids_54(t_primary_state_ids_array *v);
void	primary_state_ids_55(t_primary_state_ids_array *v);
void	primary_state_ids_56(t_primary_state_ids_array *v);
void	primary_state_ids_57(t_primary_state_ids_array *v);
void	primary_state_ids_58(t_primary_state_ids_array *v);
void	primary_state_ids_59(t_primary_state_ids_array *v);
void	primary_state_ids_60(t_primary_state_ids_array *v);
void	primary_state_ids_61(t_primary_state_ids_array *v);
void	primary_state_ids_62(t_primary_state_ids_array *v);
void	primary_state_ids_63(t_primary_state_ids_array *v);
void	primary_state_ids_64(t_primary_state_ids_array *v);
void	primary_state_ids_65(t_primary_state_ids_array *v);
void	primary_state_ids_66(t_primary_state_ids_array *v);
void	primary_state_ids_67(t_primary_state_ids_array *v);
void	primary_state_ids_68(t_primary_state_ids_array *v);
void	primary_state_ids_69(t_primary_state_ids_array *v);
void	primary_state_ids_70(t_primary_state_ids_array *v);
void	primary_state_ids_71(t_primary_state_ids_array *v);
void	primary_state_ids_72(t_primary_state_ids_array *v);
void	primary_state_ids_73(t_primary_state_ids_array *v);
void	primary_state_ids_74(t_primary_state_ids_array *v);
void	primary_state_ids_75(t_primary_state_ids_array *v);
void	primary_state_ids_76(t_primary_state_ids_array *v);
void	primary_state_ids_77(t_primary_state_ids_array *v);
void	primary_state_ids_78(t_primary_state_ids_array *v);
void	primary_state_ids_79(t_primary_state_ids_array *v);
void	primary_state_ids_80(t_primary_state_ids_array *v);
void	primary_state_ids_81(t_primary_state_ids_array *v);
void	primary_state_ids_82(t_primary_state_ids_array *v);
void	primary_state_ids_83(t_primary_state_ids_array *v);
void	primary_state_ids_84(t_primary_state_ids_array *v);
void	primary_state_ids_85(t_primary_state_ids_array *v);
void	primary_state_ids_86(t_primary_state_ids_array *v);
void	primary_state_ids_87(t_primary_state_ids_array *v);
void	primary_state_ids_88(t_primary_state_ids_array *v);
void	primary_state_ids_89(t_primary_state_ids_array *v);
void	primary_state_ids_90(t_primary_state_ids_array *v);
void	primary_state_ids_91(t_primary_state_ids_array *v);
void	primary_state_ids_92(t_primary_state_ids_array *v);
void	primary_state_ids_93(t_primary_state_ids_array *v);
void	primary_state_ids_94(t_primary_state_ids_array *v);
void	primary_state_ids_95(t_primary_state_ids_array *v);
void	primary_state_ids_96(t_primary_state_ids_array *v);
void	primary_state_ids_97(t_primary_state_ids_array *v);
void	primary_state_ids_98(t_primary_state_ids_array *v);
void	primary_state_ids_99(t_primary_state_ids_array *v);
void	primary_state_ids_100(t_primary_state_ids_array *v);
void	primary_state_ids_101(t_primary_state_ids_array *v);
void	primary_state_ids_102(t_primary_state_ids_array *v);
void	primary_state_ids_103(t_primary_state_ids_array *v);
void	primary_state_ids_104(t_primary_state_ids_array *v);
void	primary_state_ids_105(t_primary_state_ids_array *v);
void	primary_state_ids_106(t_primary_state_ids_array *v);
void	primary_state_ids_107(t_primary_state_ids_array *v);
void	primary_state_ids_108(t_primary_state_ids_array *v);
void	primary_state_ids_109(t_primary_state_ids_array *v);
void	primary_state_ids_110(t_primary_state_ids_array *v);
void	primary_state_ids_111(t_primary_state_ids_array *v);
void	primary_state_ids_112(t_primary_state_ids_array *v);
void	primary_state_ids_113(t_primary_state_ids_array *v);
void	primary_state_ids_114(t_primary_state_ids_array *v);
void	primary_state_ids_115(t_primary_state_ids_array *v);
void	primary_state_ids_116(t_primary_state_ids_array *v);
void	primary_state_ids_117(t_primary_state_ids_array *v);
void	primary_state_ids_118(t_primary_state_ids_array *v);
void	primary_state_ids_119(t_primary_state_ids_array *v);
void	primary_state_ids_120(t_primary_state_ids_array *v);
void	primary_state_ids_121(t_primary_state_ids_array *v);
void	primary_state_ids_122(t_primary_state_ids_array *v);
void	primary_state_ids_123(t_primary_state_ids_array *v);
void	primary_state_ids_124(t_primary_state_ids_array *v);
void	primary_state_ids_125(t_primary_state_ids_array *v);
void	primary_state_ids_126(t_primary_state_ids_array *v);
void	primary_state_ids_127(t_primary_state_ids_array *v);
void	primary_state_ids_128(t_primary_state_ids_array *v);
void	primary_state_ids_129(t_primary_state_ids_array *v);
void	primary_state_ids_130(t_primary_state_ids_array *v);
void	primary_state_ids_131(t_primary_state_ids_array *v);
void	primary_state_ids_132(t_primary_state_ids_array *v);
void	primary_state_ids_133(t_primary_state_ids_array *v);
void	primary_state_ids_134(t_primary_state_ids_array *v);
void	primary_state_ids_135(t_primary_state_ids_array *v);
void	primary_state_ids_136(t_primary_state_ids_array *v);
void	primary_state_ids_137(t_primary_state_ids_array *v);
void	primary_state_ids_138(t_primary_state_ids_array *v);
void	primary_state_ids_139(t_primary_state_ids_array *v);
void	primary_state_ids_140(t_primary_state_ids_array *v);
void	primary_state_ids_141(t_primary_state_ids_array *v);
void	primary_state_ids_142(t_primary_state_ids_array *v);
void	primary_state_ids_143(t_primary_state_ids_array *v);
void	primary_state_ids_144(t_primary_state_ids_array *v);
void	primary_state_ids_145(t_primary_state_ids_array *v);
void	primary_state_ids_146(t_primary_state_ids_array *v);
void	primary_state_ids_147(t_primary_state_ids_array *v);
void	primary_state_ids_148(t_primary_state_ids_array *v);
void	primary_state_ids_149(t_primary_state_ids_array *v);
void	primary_state_ids_150(t_primary_state_ids_array *v);
void	primary_state_ids_151(t_primary_state_ids_array *v);
void	primary_state_ids_152(t_primary_state_ids_array *v);
void	primary_state_ids_153(t_primary_state_ids_array *v);
void	primary_state_ids_154(t_primary_state_ids_array *v);
void	primary_state_ids_155(t_primary_state_ids_array *v);
void	primary_state_ids_156(t_primary_state_ids_array *v);
void	primary_state_ids_157(t_primary_state_ids_array *v);
void	primary_state_ids_158(t_primary_state_ids_array *v);
void	primary_state_ids_159(t_primary_state_ids_array *v);
void	primary_state_ids_160(t_primary_state_ids_array *v);
void	primary_state_ids_161(t_primary_state_ids_array *v);
void	primary_state_ids_162(t_primary_state_ids_array *v);
void	primary_state_ids_163(t_primary_state_ids_array *v);
void	primary_state_ids_164(t_primary_state_ids_array *v);
void	primary_state_ids_165(t_primary_state_ids_array *v);
void	primary_state_ids_166(t_primary_state_ids_array *v);
void	primary_state_ids_167(t_primary_state_ids_array *v);
void	primary_state_ids_168(t_primary_state_ids_array *v);
void	primary_state_ids_169(t_primary_state_ids_array *v);
void	primary_state_ids_170(t_primary_state_ids_array *v);
void	primary_state_ids_171(t_primary_state_ids_array *v);
void	primary_state_ids_172(t_primary_state_ids_array *v);
void	primary_state_ids_173(t_primary_state_ids_array *v);
void	primary_state_ids_174(t_primary_state_ids_array *v);
void	primary_state_ids_175(t_primary_state_ids_array *v);
void	primary_state_ids_176(t_primary_state_ids_array *v);
void	primary_state_ids_177(t_primary_state_ids_array *v);
void	primary_state_ids_178(t_primary_state_ids_array *v);
void	primary_state_ids_179(t_primary_state_ids_array *v);
void	primary_state_ids_180(t_primary_state_ids_array *v);
void	primary_state_ids_181(t_primary_state_ids_array *v);
void	primary_state_ids_182(t_primary_state_ids_array *v);
void	primary_state_ids_183(t_primary_state_ids_array *v);
void	primary_state_ids_184(t_primary_state_ids_array *v);
void	primary_state_ids_185(t_primary_state_ids_array *v);
void	primary_state_ids_186(t_primary_state_ids_array *v);
void	primary_state_ids_187(t_primary_state_ids_array *v);
void	primary_state_ids_188(t_primary_state_ids_array *v);
void	primary_state_ids_189(t_primary_state_ids_array *v);
void	primary_state_ids_190(t_primary_state_ids_array *v);
void	primary_state_ids_191(t_primary_state_ids_array *v);
void	primary_state_ids_192(t_primary_state_ids_array *v);
void	primary_state_ids_193(t_primary_state_ids_array *v);
void	primary_state_ids_194(t_primary_state_ids_array *v);
void	primary_state_ids_195(t_primary_state_ids_array *v);
void	primary_state_ids_196(t_primary_state_ids_array *v);
void	primary_state_ids_197(t_primary_state_ids_array *v);
void	primary_state_ids_198(t_primary_state_ids_array *v);
void	primary_state_ids_199(t_primary_state_ids_array *v);
void	primary_state_ids_200(t_primary_state_ids_array *v);
void	primary_state_ids_201(t_primary_state_ids_array *v);
void	primary_state_ids_202(t_primary_state_ids_array *v);
void	primary_state_ids_203(t_primary_state_ids_array *v);
void	primary_state_ids_204(t_primary_state_ids_array *v);

#endif // PRIMARY_STATE_IDS_H
