SRC_FILES =                                                                   \
_not_done_function                                                            \
_not_done_print                                                               \
ast_alloc/ast_alloc                                                           \
ast_alloc/ast_alloc_scripting                                                 \
ast_free/ast_free                                                             \
ast_free/ast_free_scripting                                                   \
from_node/arithmetic_node2                                                    \
from_node/artihmetic_node                                                     \
from_node/boucle_node                                                         \
from_node/condition_node                                                      \
from_node/dev_node                                                            \
from_node/expand_node                                                         \
from_node/expansion_node                                                      \
from_node/file_node                                                           \
from_node/from_node                                                           \
from_node/node_utils                                                          \
from_node/node_utils2                                                         \
from_node/redirect_node                                                       \
from_node/scripting_node                                                      \
print_ast/ast_print_command                                                   \
print_ast/ast_print_global                                                    \
print_ast/ast_print_node                                                      \
print_ast/ast_print_redirection                                               \
print_ast/ast_print_subshell                                                  \
print_ast/helper_function_print                                               \
print_ast/print_arithmetic                                                    \
print_ast/print_ast                                                           \

