SRC_FILES =                                                                   \
language/language_field                                                       \
language/language_getters                                                     \
language/language_getters2                                                    \
language/language_misc                                                        \
language/language_symbol                                                      \
language/language_symbol2                                                     \
length/length_funcs1                                                          \
length/length_funcs2                                                          \
lex                                                                           \
lexer/lexer_advance                                                           \
lexer/lexer_chunk                                                             \
lexer/lexer_end                                                               \
lexer/lexer_get_column                                                        \
lexer/lexer_goto                                                              \
lexer/lexer_lifetime                                                          \
lexer/lexer_lookahead                                                         \
misc/create_language                                                          \
misc/external_scanner_state                                                   \
misc/external_scanner_state2                                                  \
misc/input                                                                    \
misc/reduce_action                                                            \
node/node_child                                                               \
node/node_child_inner                                                         \
node/node_constructor                                                         \
node/node_fields                                                              \
node/node_getter_funcs1                                                       \
node/node_getter_funcs2                                                       \
node/node_getter_funcs3                                                       \
node/node_iterator                                                            \
node/node_relevent                                                            \
parser/parser_accept                                                          \
parser/parser_advance                                                         \
parser/parser_breakdown_top_of_stack                                          \
parser/parser_condense_stack                                                  \
parser/parser_do_reduction                                                    \
parser/parser_external_scanner                                                \
parser/parser_handle_error                                                    \
parser/parser_lex                                                             \
parser/parser_lifetime                                                        \
parser/parser_outstanding_parse                                               \
parser/parser_parse                                                           \
parser/parser_parse_str                                                       \
parser/parser_recover                                                         \
parser/parser_recover_to_tree                                                 \
parser/parser_reduce                                                          \
parser/parser_select                                                          \
parser/parser_shift                                                           \
parser/parser_versions                                                        \
point/point_funcs1                                                            \
point/point_funcs2                                                            \
scanner/scanner                                                               \
stack/stack_add_link                                                          \
stack/stack_funcs1                                                            \
stack/stack_funcs2                                                            \
stack/stack_funcs3                                                            \
stack/stack_funcs4                                                            \
stack/stack_iter                                                              \
stack/stack_lifetime                                                          \
stack/stack_manipulate                                                        \
stack/stack_manipulate2                                                       \
stack/stack_manipulate3                                                       \
stack/stack_node                                                              \
stack/stack_summary                                                           \
stack/stack_version                                                           \
subtree/subtree_balance                                                       \
subtree/subtree_funcs                                                         \
subtree/subtree_helper                                                        \
subtree/subtree_new                                                           \
subtree/subtree_summarize                                                     \
subtree/subtree_vec_helper                                                    \
tree/tree_funcs1                                                              \
tree/tree_funcs2                                                              \

GEN_FILES =                                                                   \
                                                                              \

