/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   field_map_entries.c                                :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maiboyer <maiboyer@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/04/14 19:17:54 by maiboyer          #+#    #+#             */
/*   Updated: 2024/04/14 19:18:20 by maiboyer         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../types/type_field_map_entries.h"
#include "../headers/symbols.h"
#include "../headers/external_scanner_symbol_identifiers.h"
#include "../headers/field_identifiers.h"

#include "../headers/constants.h"

static const \
t_field_map_entries_array	g_t_field_map_entries_array = {.a = {
[0] = {.field_id = field_stmt, .child_index = 0, .inherited = true},
[1] = {.field_id = field_term, .child_index = 0, .inherited = true},
[2] = {.field_id = field_stmt, .child_index = 0, .inherited = false},
[3] = {.field_id = field_name, .child_index = 0, .inherited = false},
[4] = {.field_id = field_redr, .child_index = 0, .inherited = false},
[5] = {.field_id = field_dest, .child_index = 1, .inherited = false},
[6] = {.field_id = field_op, .child_index = 0, .inherited = false},
[7] = {.field_id = field_stmt, .child_index = 0, .inherited = false},
[8] = {.field_id = field_term, .child_index = 1, .inherited = false},
[9] = {.field_id = field_body, .child_index = 0, .inherited = false},
[10] = {.field_id = field_redr, .child_index = 1, .inherited = false},
[11] = {.field_id = field_arg, .child_index = 0, .inherited = false},
[12] = {.field_id = field_arg, .child_index = 1, .inherited = true},
[13] = {.field_id = field_name, .child_index = 0, .inherited = false},
[14] = {.field_id = field_stmt, .child_index = 0, .inherited = true},
[15] = {.field_id = field_stmt, .child_index = 1, .inherited = false},
[16] = {.field_id = field_term, .child_index = 0, .inherited = true},
[17] = {.field_id = field_stmt, .child_index = 0, .inherited = true},
[18] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[19] = {.field_id = field_term, .child_index = 0, .inherited = true},
[20] = {.field_id = field_term, .child_index = 1, .inherited = true},
[21] = {.field_id = field_name, .child_index = 1, .inherited = false},
[22] = {.field_id = field_redr, .child_index = 0, .inherited = true},
[23] = {.field_id = field_redr, .child_index = 0, .inherited = true},
[24] = {.field_id = field_redr, .child_index = 1, .inherited = true},
[25] = {.field_id = field_name, .child_index = 0, .inherited = false},
[26] = {.field_id = field_value, .child_index = 2, .inherited = false},
[27] = {.field_id = field_body, .child_index = 2, .inherited = false},
[28] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[29] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[30] = {.field_id = field_term, .child_index = 1, .inherited = true},
[31] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[32] = {.field_id = field_term, .child_index = 1, .inherited = true},
[33] = {.field_id = field_op, .child_index = 0, .inherited = false},
[34] = {.field_id = field_op, .child_index = 1, .inherited = false},
[35] = {.field_id = field_args, .child_index = 1, .inherited = true},
[36] = {.field_id = field_name, .child_index = 0, .inherited = false},
[37] = {.field_id = field_op, .child_index = 1, .inherited = true},
[38] = {.field_id = field_len, .child_index = 0, .inherited = false},
[39] = {.field_id = field_name, .child_index = 1, .inherited = false},
[40] = {.field_id = field_args, .child_index = 1, .inherited = true},
[41] = {.field_id = field_len, .child_index = 1, .inherited = true},
[42] = {.field_id = field_name, .child_index = 1, .inherited = true},
[43] = {.field_id = field_op, .child_index = 1, .inherited = true},
[44] = {.field_id = field_redr, .child_index = 1, .inherited = false},
[45] = {.field_id = field_cmd, .child_index = 0, .inherited = false},
[46] = {.field_id = field_cmd, .child_index = 2, .inherited = false},
[47] = {.field_id = field_op, .child_index = 1, .inherited = false},
[48] = {.field_id = field_arg, .child_index = 0, .inherited = true},
[49] = {.field_id = field_arg, .child_index = 1, .inherited = true},
[50] = {.field_id = field_stmt, .child_index = 0, .inherited = true},
[51] = {.field_id = field_stmt, .child_index = 1, .inherited = false},
[52] = {.field_id = field_term, .child_index = 0, .inherited = true},
[53] = {.field_id = field_term, .child_index = 2, .inherited = false},
[54] = {.field_id = field_arg, .child_index = 2, .inherited = true},
[55] = {.field_id = field_name, .child_index = 1, .inherited = false},
[56] = {.field_id = field_redr, .child_index = 0, .inherited = true},
[57] = {.field_id = field_body, .child_index = 3, .inherited = false},
[58] = {.field_id = field_var, .child_index = 1, .inherited = false},
[59] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[60] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[61] = {.field_id = field_term, .child_index = 1, .inherited = true},
[62] = {.field_id = field_value, .child_index = 1, .inherited = false},
[63] = {.field_id = field_cases, .child_index = 0, .inherited = false},
[64] = {.field_id = field_lhs, .child_index = 0, .inherited = false},
[65] = {.field_id = field_op, .child_index = 1, .inherited = false},
[66] = {.field_id = field_rhs, .child_index = 2, .inherited = false},
[67] = {.field_id = field_args, .child_index = 1, .inherited = false},
[68] = {.field_id = field_op, .child_index = 0, .inherited = false},
[69] = {.field_id = field_args, .child_index = 2, .inherited = true},
[70] = {.field_id = field_len, .child_index = 0, .inherited = false},
[71] = {.field_id = field_name, .child_index = 1, .inherited = false},
[72] = {.field_id = field_op, .child_index = 2, .inherited = true},
[73] = {.field_id = field_body, .child_index = 3, .inherited = false},
[74] = {.field_id = field_name, .child_index = 0, .inherited = false},
[75] = {.field_id = field_body, .child_index = 1, .inherited = false},
[76] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[77] = {.field_id = field_term, .child_index = 1, .inherited = true},
[78] = {.field_id = field_body, .child_index = 3, .inherited = false},
[79] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[80] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[81] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[82] = {.field_id = field_term, .child_index = 1, .inherited = true},
[83] = {.field_id = field_term, .child_index = 3, .inherited = true},
[84] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[85] = {.field_id = field_else, .child_index = 3, .inherited = false},
[86] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[87] = {.field_id = field_term, .child_index = 1, .inherited = true},
[88] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[89] = {.field_id = field_elif, .child_index = 3, .inherited = false},
[90] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[91] = {.field_id = field_term, .child_index = 1, .inherited = true},
[92] = {.field_id = field_body, .child_index = 3, .inherited = true},
[93] = {.field_id = field_cases, .child_index = 3, .inherited = false},
[94] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[95] = {.field_id = field_term, .child_index = 3, .inherited = true},
[96] = {.field_id = field_value, .child_index = 1, .inherited = false},
[97] = {.field_id = field_value, .child_index = 3, .inherited = true},
[98] = {.field_id = field_cases, .child_index = 0, .inherited = true},
[99] = {.field_id = field_cases, .child_index = 1, .inherited = true},
[100] = {.field_id = field_op, .child_index = 0, .inherited = false},
[101] = {.field_id = field_rhs, .child_index = 1, .inherited = false},
[102] = {.field_id = field_body, .child_index = 5, .inherited = false},
[103] = {.field_id = field_value, .child_index = 3, .inherited = false},
[104] = {.field_id = field_var, .child_index = 1, .inherited = false},
[105] = {.field_id = field_body, .child_index = 3, .inherited = false},
[106] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[107] = {.field_id = field_else, .child_index = 4, .inherited = false},
[108] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[109] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[110] = {.field_id = field_term, .child_index = 1, .inherited = true},
[111] = {.field_id = field_term, .child_index = 3, .inherited = true},
[112] = {.field_id = field_body, .child_index = 3, .inherited = false},
[113] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[114] = {.field_id = field_elif, .child_index = 4, .inherited = false},
[115] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[116] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[117] = {.field_id = field_term, .child_index = 1, .inherited = true},
[118] = {.field_id = field_term, .child_index = 3, .inherited = true},
[119] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[120] = {.field_id = field_elif, .child_index = 3, .inherited = false},
[121] = {.field_id = field_else, .child_index = 4, .inherited = false},
[122] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[123] = {.field_id = field_term, .child_index = 1, .inherited = true},
[124] = {.field_id = field_body, .child_index = 2, .inherited = false},
[125] = {.field_id = field_stmt, .child_index = 2, .inherited = true},
[126] = {.field_id = field_term, .child_index = 2, .inherited = true},
[127] = {.field_id = field_value, .child_index = 0, .inherited = false},
[128] = {.field_id = field_value, .child_index = 0, .inherited = true},
[129] = {.field_id = field_value, .child_index = 1, .inherited = true},
[130] = {.field_id = field_body, .child_index = 4, .inherited = true},
[131] = {.field_id = field_cases, .child_index = 4, .inherited = false},
[132] = {.field_id = field_stmt, .child_index = 4, .inherited = true},
[133] = {.field_id = field_term, .child_index = 4, .inherited = true},
[134] = {.field_id = field_value, .child_index = 1, .inherited = false},
[135] = {.field_id = field_value, .child_index = 4, .inherited = true},
[136] = {.field_id = field_body, .child_index = 4, .inherited = true},
[137] = {.field_id = field_cases, .child_index = 3, .inherited = true},
[138] = {.field_id = field_cases, .child_index = 4, .inherited = false},
[139] = {.field_id = field_stmt, .child_index = 4, .inherited = true},
[140] = {.field_id = field_term, .child_index = 4, .inherited = true},
[141] = {.field_id = field_value, .child_index = 1, .inherited = false},
[142] = {.field_id = field_value, .child_index = 4, .inherited = true},
[143] = {.field_id = field_cond, .child_index = 0, .inherited = false},
[144] = {.field_id = field_else, .child_index = 4, .inherited = false},
[145] = {.field_id = field_then, .child_index = 2, .inherited = false},
[146] = {.field_id = field_op, .child_index = 0, .inherited = false},
[147] = {.field_id = field_op, .child_index = 2, .inherited = true},
[148] = {.field_id = field_rhs, .child_index = 2, .inherited = true},
[149] = {.field_id = field_arg, .child_index = 2, .inherited = true},
[150] = {.field_id = field_op, .child_index = 0, .inherited = false},
[151] = {.field_id = field_op, .child_index = 0, .inherited = false},
[152] = {.field_id = field_redr, .child_index = 2, .inherited = false},
[153] = {.field_id = field_body, .child_index = 3, .inherited = false},
[154] = {.field_id = field_cond, .child_index = 1, .inherited = false},
[155] = {.field_id = field_elif, .child_index = 4, .inherited = false},
[156] = {.field_id = field_else, .child_index = 5, .inherited = false},
[157] = {.field_id = field_stmt, .child_index = 1, .inherited = true},
[158] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[159] = {.field_id = field_term, .child_index = 1, .inherited = true},
[160] = {.field_id = field_term, .child_index = 3, .inherited = true},
[161] = {.field_id = field_body, .child_index = 3, .inherited = false},
[162] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[163] = {.field_id = field_term, .child_index = 3, .inherited = true},
[164] = {.field_id = field_value, .child_index = 1, .inherited = false},
[165] = {.field_id = field_body, .child_index = 3, .inherited = false},
[166] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[167] = {.field_id = field_term, .child_index = 3, .inherited = true},
[168] = {.field_id = field_value, .child_index = 0, .inherited = false},
[169] = {.field_id = field_body, .child_index = 3, .inherited = false},
[170] = {.field_id = field_stmt, .child_index = 3, .inherited = true},
[171] = {.field_id = field_term, .child_index = 3, .inherited = true},
[172] = {.field_id = field_value, .child_index = 0, .inherited = false},
[173] = {.field_id = field_value, .child_index = 1, .inherited = true},
[174] = {.field_id = field_body, .child_index = 5, .inherited = true},
[175] = {.field_id = field_cases, .child_index = 4, .inherited = true},
[176] = {.field_id = field_cases, .child_index = 5, .inherited = false},
[177] = {.field_id = field_stmt, .child_index = 5, .inherited = true},
[178] = {.field_id = field_term, .child_index = 5, .inherited = true},
[179] = {.field_id = field_value, .child_index = 1, .inherited = false},
[180] = {.field_id = field_value, .child_index = 5, .inherited = true},
[181] = {.field_id = field_body, .child_index = 5, .inherited = true},
[182] = {.field_id = field_cases, .child_index = 5, .inherited = false},
[183] = {.field_id = field_stmt, .child_index = 5, .inherited = true},
[184] = {.field_id = field_term, .child_index = 5, .inherited = true},
[185] = {.field_id = field_value, .child_index = 1, .inherited = false},
[186] = {.field_id = field_value, .child_index = 5, .inherited = true},
[187] = {.field_id = field_op, .child_index = 0, .inherited = false},
[188] = {.field_id = field_op, .child_index = 3, .inherited = true},
[189] = {.field_id = field_redr, .child_index = 2, .inherited = false},
[190] = {.field_id = field_rhs, .child_index = 3, .inherited = true},
[191] = {.field_id = field_body, .child_index = 4, .inherited = false},
[192] = {.field_id = field_stmt, .child_index = 4, .inherited = true},
[193] = {.field_id = field_term, .child_index = 4, .inherited = true},
[194] = {.field_id = field_value, .child_index = 1, .inherited = false},
[195] = {.field_id = field_body, .child_index = 4, .inherited = false},
[196] = {.field_id = field_stmt, .child_index = 4, .inherited = true},
[197] = {.field_id = field_term, .child_index = 4, .inherited = true},
[198] = {.field_id = field_value, .child_index = 1, .inherited = false},
[199] = {.field_id = field_value, .child_index = 2, .inherited = true},
[200] = {.field_id = field_body, .child_index = 4, .inherited = false},
[201] = {.field_id = field_stmt, .child_index = 4, .inherited = true},
[202] = {.field_id = field_term, .child_index = 4, .inherited = true},
[203] = {.field_id = field_value, .child_index = 0, .inherited = false},
[204] = {.field_id = field_value, .child_index = 1, .inherited = true},
[205] = {.field_id = field_body, .child_index = 6, .inherited = true},
[206] = {.field_id = field_cases, .child_index = 5, .inherited = true},
[207] = {.field_id = field_cases, .child_index = 6, .inherited = false},
[208] = {.field_id = field_stmt, .child_index = 6, .inherited = true},
[209] = {.field_id = field_term, .child_index = 6, .inherited = true},
[210] = {.field_id = field_value, .child_index = 1, .inherited = false},
[211] = {.field_id = field_value, .child_index = 6, .inherited = true},
[212] = {.field_id = field_body, .child_index = 5, .inherited = false},
[213] = {.field_id = field_stmt, .child_index = 5, .inherited = true},
[214] = {.field_id = field_term, .child_index = 5, .inherited = true},
[215] = {.field_id = field_value, .child_index = 1, .inherited = false},
[216] = {.field_id = field_value, .child_index = 2, .inherited = true},
}};

const t_field_map_entries_array	*create_field_map_entries(void)
{
	return (&g_t_field_map_entries_array);
}
