/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   symbols_metadata.c                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maiboyer <maiboyer@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/04/14 19:17:54 by maiboyer          #+#    #+#             */
/*   Updated: 2024/04/14 19:18:20 by maiboyer         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../types/type_symbols_metadata.h"
#include "../headers/symbols.h"
#include "../headers/external_scanner_symbol_identifiers.h"
#include "../headers/field_identifiers.h"

#include "../headers/constants.h"

static const \
t_symbols_metadata_array	g_t_symbols_metadata_array = {.a = {
[ts_builtin_sym_end] = {false, true, false},
[sym_word] = {true, true, false},
[anon_sym_for] = {true, false, false},
[anon_sym_in] = {true, false, false},
[anon_sym_while] = {true, false, false},
[anon_sym_until] = {true, false, false},
[anon_sym_do] = {true, false, false},
[anon_sym_done] = {true, false, false},
[anon_sym_if] = {true, false, false},
[anon_sym_then] = {true, false, false},
[anon_sym_fi] = {true, false, false},
[anon_sym_elif] = {true, false, false},
[anon_sym_else] = {true, false, false},
[anon_sym_case] = {true, false, false},
[anon_sym_esac] = {true, false, false},
[anon_sym_LPAREN] = {true, false, false},
[anon_sym_PIPE] = {true, false, false},
[anon_sym_RPAREN] = {true, false, false},
[anon_sym_LF] = {true, false, false},
[anon_sym_SEMI_SEMI] = {true, false, false},
[anon_sym_LBRACE] = {true, false, false},
[anon_sym_RBRACE] = {true, false, false},
[anon_sym_AMP_AMP] = {true, true, false},
[anon_sym_PIPE_PIPE] = {true, true, false},
[anon_sym_BANG] = {true, false, false},
[anon_sym_EQ] = {true, false, false},
[anon_sym_LT] = {true, true, false},
[anon_sym_GT] = {true, true, false},
[anon_sym_GT_GT] = {true, true, false},
[anon_sym_LT_LT] = {true, true, false},
[aux_sym_heredoc_redirect_token1] = {false, false, false},
[anon_sym_DOLLAR_LPAREN_LPAREN] = {true, false, false},
[anon_sym_RPAREN_RPAREN] = {true, false, false},
[anon_sym_PLUS] = {true, true, false},
[anon_sym_DASH] = {true, true, false},
[anon_sym_STAR] = {true, true, false},
[anon_sym_SLASH] = {true, true, false},
[anon_sym_PERCENT] = {true, true, false},
[anon_sym_QMARK] = {true, false, false},
[anon_sym_COLON] = {true, false, false},
[anon_sym_DASH2] = {true, true, false},
[anon_sym_PLUS2] = {true, true, false},
[anon_sym_PLUS_PLUS] = {true, true, false},
[anon_sym_DASH_DASH] = {true, true, false},
[aux_sym_concatenation_token1] = {true, false, false},
[anon_sym_DOLLAR] = {true, false, false},
[anon_sym_DQUOTE] = {true, false, false},
[sym_string_content] = {true, true, false},
[sym_raw_string] = {true, true, false},
[sym_number] = {true, true, false},
[anon_sym_POUND] = {true, true, false},
[anon_sym_DOLLAR_LBRACE] = {true, false, false},
[anon_sym_COLON_DASH] = {true, true, false},
[anon_sym_DASH3] = {true, true, false},
[anon_sym_COLON_EQ] = {true, true, false},
[anon_sym_EQ2] = {true, true, false},
[anon_sym_COLON_QMARK] = {true, true, false},
[anon_sym_QMARK2] = {true, true, false},
[anon_sym_COLON_PLUS] = {true, true, false},
[anon_sym_PLUS3] = {true, true, false},
[anon_sym_PERCENT_PERCENT] = {true, true, false},
[aux_sym__expansion_regex_token1] = {true, true, false},
[anon_sym_DOLLAR_LPAREN] = {true, false, false},
[anon_sym_BQUOTE] = {true, false, false},
[sym_comment] = {true, true, false},
[sym__comment_word] = {true, true, false},
[aux_sym__simple_variable_name_token1] = {true, true, false},
[aux_sym__multiline_variable_name_token1] = {true, true, false},
[anon_sym_AT] = {true, true, false},
[anon_sym_0] = {true, true, false},
[aux_sym__word_no_brace_token1] = {false, false, false},
[anon_sym_SEMI] = {true, false, false},
[anon_sym_LT_LT_DASH] = {true, false, false},
[sym_heredoc_start] = {true, true, false},
[sym_simple_heredoc_body] = {true, true, false},
[sym__heredoc_body_beginning] = {false, true, false},
[sym_heredoc_content] = {true, true, false},
[sym_heredoc_end] = {true, true, false},
[sym_file_descriptor] = {true, true, false},
[sym__empty_value] = {false, true, false},
[sym__concat] = {false, true, false},
[sym_variable_name] = {true, true, false},
[sym_regex] = {true, true, false},
[sym__expansion_word] = {true, true, false},
[sym_extglob_pattern] = {true, true, false},
[sym__bare_dollar] = {true, true, false},
[sym__immediate_double_hash] = {true, true, false},
[sym___error_recovery] = {false, true, false},
[sym_program] = {true, true, false},
[sym__statements] = {false, true, false},
[aux_sym__terminated_statement] = {false, false, false},
[sym__statement_not_pipeline] = {false, true, false},
[sym_redirected_statement] = {true, true, false},
[sym_for_statement] = {true, true, false},
[sym_while_statement] = {true, true, false},
[sym_do_group] = {true, true, false},
[sym_if_statement] = {true, true, false},
[sym_elif_clause] = {true, true, false},
[sym_else_clause] = {true, true, false},
[sym_case_statement] = {true, true, false},
[sym__case_item_last] = {true, true, false},
[sym_case_item] = {true, true, false},
[sym_function_definition] = {true, true, false},
[sym_compound_statement] = {true, true, false},
[sym_subshell] = {true, true, false},
[sym_pipeline] = {true, true, false},
[sym_list] = {true, true, false},
[sym_negated_command] = {true, true, false},
[sym_command] = {true, true, false},
[sym_command_name] = {true, true, false},
[sym_variable_assignment] = {true, true, false},
[sym__variable_assignments] = {false, true, false},
[sym_file_redirect] = {true, true, false},
[sym_heredoc_redirect] = {true, true, false},
[sym__heredoc_pipeline] = {true, true, false},
[sym__heredoc_expression] = {false, true, false},
[aux_sym__heredoc_command] = {false, false, false},
[sym__heredoc_body] = {false, true, false},
[sym_heredoc_body] = {true, true, false},
[sym__simple_heredoc_body] = {false, true, false},
[sym_arithmetic_expansion] = {true, true, false},
[sym__arithmetic_expression] = {false, true, false},
[sym_arithmetic_literal] = {true, true, false},
[sym_arithmetic_binary_expression] = {true, true, false},
[sym_arithmetic_ternary_expression] = {true, true, false},
[sym_arithmetic_unary_expression] = {true, true, false},
[sym_arithmetic_postfix_expression] = {true, true, false},
[sym_arithmetic_parenthesized_expression] = {true, true, false},
[sym_concatenation] = {true, true, false},
[sym_string] = {true, true, false},
[sym_simple_expansion] = {true, true, false},
[sym_expansion] = {true, true, false},
[sym__expansion_body] = {false, true, false},
[sym__expansion_expression] = {false, true, false},
[sym__expansion_regex] = {false, true, false},
[sym__concatenation_in_expansion] = {true, true, false},
[sym_command_substitution] = {true, true, false},
[sym__extglob_blob] = {false, true, false},
[sym__word_no_brace] = {true, true, false},
[sym_terminator] = {true, true, false},
[aux_sym__statements_repeat1] = {false, false, false},
[aux_sym_redirected_statement_repeat1] = {false, false, false},
[aux_sym_redirected_statement_repeat2] = {false, false, false},
[aux_sym_for_statement_repeat1] = {false, false, false},
[aux_sym_if_statement_repeat1] = {false, false, false},
[aux_sym_case_statement_repeat1] = {false, false, false},
[aux_sym__case_item_last_repeat1] = {false, false, false},
[aux_sym__case_item_last_repeat2] = {false, false, false},
[aux_sym_pipeline_repeat1] = {false, false, false},
[aux_sym_command_repeat1] = {false, false, false},
[aux_sym_command_repeat2] = {false, false, false},
[aux_sym__variable_assignments_repeat1] = {false, false, false},
[aux_sym_heredoc_body_repeat1] = {false, false, false},
[aux_sym_concatenation_repeat1] = {false, false, false},
[aux_sym_string_repeat1] = {false, false, false},
[aux_sym__expansion_regex_repeat1] = {false, false, false},
[aux_sym__concatenation_in_expansion_repeat1] = {false, false, false},
}};

const t_symbols_metadata_array	*create_symbols_metadata(void)
{
	return (&g_t_symbols_metadata_array);
}
